### ISSUE TITLE
Add support for INA226 DC current sensor

### ISSUE THREAD

**Issue by ba58smith** [SignalK/SensESP#111]
Requested by someone on Slack.

**Comment by ba58smith** [comment]
Having issues with the INA226 library. Don't merge this until that is resolved.

**Comment by ba58smith** [comment]
UPDATE: I've created a new Sensor (INA2xx) that will work with ALL of the INA2xx sensors, as well as the INA3221 3-channel sensor. It's being created as the first "external SensESP library". When it's finished, it will close this Issue. See https://github.com/SensESP/INA2xx.

**Comment by AAlbero** [comment]
@ba58smith I was not able to find this. The link you posted is 404. Can you help? Anything I do to add INA226 in my SensESP projects place my SH-ESP32 in a reboot loop. Thanks.

**Comment by ba58smith** [comment]
Sorry, I can't find it either. I'm guessing it was moved or made obsolete when the whole SensESP project was reorganized several months ago. Maybe @mairas can remember what happened to it.
