### ISSUE TITLE
Add support for Nasa Depth Output

### ISSUE THREAD

**Issue by pshotton** [SignalK/SensESP#139]
An article on the OpenSeaMap wiki explains how to decode the Nasa Clipper Depth repeater output to generate NMEA depth sentences, See http://wiki.openseamap.org/wiki/De:NASA_Clipper_Range. I have modified this code to be used as a sensor within SensESP. This issue is opened to tag the code that I will submit just as soon as I can test on my boat!

**Comment by ba58smith** [comment]
Very stale. Closing.
