### ISSUE TITLE
Update to ArduinoJson ver 6

### ISSUE THREAD

**Issue by ba58smith** [SignalK/SensESP#163]
SensESP uses ver 5, and 6 is not backwards-compatible with 5. Until we update to 6, everyone will always have to uninstall 6 if (when) it's installed automatically by PlatformIO.

I will take an initial stab at it.

**Comment by JohnySeven** [comment]
PR #172 is dealing with this one.

**Comment by mairas** [comment]
Fixed in PR #172.

**Comment by mairas** [comment]
Doh, PR #172 was against some other branch than master. Reopening. @JohnySeven could you please make a new PR with identical contents against the master branch?

**Comment by JohnySeven** [comment]
@mairas sure, I can do it. @ba58smith  asked for it :-)

**Comment by JohnySeven** [comment]
@mairas see PR #175

**Comment by mairas** [comment]
Fixed in PR #175
