### ISSUE TITLE
Time to update version to 1.0?

### ISSUE THREAD

**Issue by ba58smith** [SignalK/SensESP#164]
@mairas - should we decide on anything else that's necessary prior to changing the version to 1.0, then do that? 
- Update the README
- Update the Wiki
- Generate new class documentation
- Update all current examples to use Builder
- what else?

**Comment by ba58smith** [comment]
Version was updated to 0.5.0. Closing.

**Comment by mairas** [comment]
Nah, I'm reopening - 1.0.0 should still be very much in the pipeline, and this issue is a good reminder about that. I just thought there'd be too many opportunities for messing up the release if we went straight to the big one. :-)

**Comment by ba58smith** [comment]
Closed with PR #331.
