### ISSUE TITLE
SensESP projects fail to build on PlatformIO 5.0.1

### ISSUE THREAD

**Issue by mairas** [SignalK/SensESP#168]
This is due to a regression in PlatformIO Core. See: https://github.com/platformio/platformio-core/issues/3668

**Comment by mairas** [comment]
A temporary fix was made in PR #170. I'll leave this issue open to remind us to remove the indirect dependencies once the underlying PlatformIO issue has been fixed.

**Comment by ba58smith** [comment]
@mairas - this is now fixed, isn't it?

**Comment by mairas** [comment]
Yep, I would say so. Fingers crossed.

Closing!
