### ISSUE TITLE
Allow device to fill in requested permissions in token request to server

### ISSUE THREAD

**Issue by JohnySeven** [SignalK/SensESP#173]
Hello,

it's just small think but it will allow devices to define what SK permissions they need in order to work, some of them needs just "readonly", mostly they need "readwrite" or "admin".

My sugestion is to change the token request to provide "permissions" in JSON token request and add new method in SensESP builder to configure this. Default permission will be "readwrite" as most devices needs to pull the data in.

This scenario is supported by SK server here:
(https://github.com/SignalK/signalk-server/blob/1c80214bd86272c04c47b8cf8be363e617d202a3/src/tokensecurity.js#L1035)

Just let me know what you think about this.

I'm willing to make PR.

Thanks,
Jan

**Comment by ba58smith** [comment]
I like this - it will mean one less step in getting a new ESP sending data to Signal K.

**Comment by mairas** [comment]
Oh, I didn't know that was supported! That's annoyed me forever. I'd love it too.

**Comment by ba58smith** [comment]
Closed with PR #201.
