### ISSUE TITLE
SensESP config page issue

### ISSUE THREAD

**Issue by tedenda** [SignalK/SensESP#192]
A SensESP node with an BME280 sensor attached generates faulty foldout meny on config page.
Humidity value is listed outside the foldout where pressure and temperature is listed:

![Skärmavbild 2020-10-07 kl  12 15 10](https://user-images.githubusercontent.com/4216986/95319980-10cfbb80-0899-11eb-9aa4-69e683938b3e.png)

The humidity link is not working:

![Skärmavbild 2020-10-07 kl  12 34 34](https://user-images.githubusercontent.com/4216986/95320539-e7635f80-0899-11eb-95bc-93339e4a40f4.png)

**Comment by ba58smith** [comment]
Please show me the part of your main.cpp where you've created the BME280Value. You may not have the config_path quite right. (Does it start with a "/"?)

**Comment by tedenda** [comment]
Good catch!

I will make a PR to fix the example code!

```
  // Do the same for the humidity value.
  auto* bme_humidity =
      new BME280Value(bme280, humidity, read_delay, "Outside/Humidity");

  bme_humidity->connect_to(new SKOutputNumber("environment.outside.humidity"));
```

**Comment by tedenda** [comment]
Its now correct:
![Skärmavbild 2020-10-07 kl  15 53 24](https://user-images.githubusercontent.com/4216986/95341052-28696d00-08b6-11eb-9cfb-731df10873ff.png)

I have fixed a PR for this issue:
https://github.com/SignalK/SensESP/pull/193

**Comment by ba58smith** [comment]
Nice catch - thanks!
