### ISSUE TITLE
SensorNXP_FXOS8700_FXAS21002 code must be formatted according to project standards

### ISSUE THREAD

**Issue by mairas** [SignalK/SensESP#244]
I was led to believe that code in `src/sensors/sensor_nxp_fxos8700_fxas21002.h.*` was copied pretty much verbatim from some Adafruit examples and that's why the code was not formatted according to the project standards. Given the comments in PR #166, this is obviously not the case. Hence, the code must be reformatted and and variables renamed to follow [Google C++ Style Guide](https://google.github.io/styleguide/cppguide.html) used throughout SensESP.

**Comment by BjarneBitscrambler** [comment]
I have my port of NXP's sensor fusion v7 algorithm encapsulated in a library for ESP32/ESP8266 (https://github.com/BjarneBitscrambler/OrientationSensorFusion-ESP.git)  This will allow me to change the SensESP orientation example to use the new library, and remove dependencies on the AdaFruit AHRS and related libraries plus the offending `src/sensors/sensor_nxp_fxos8700_fxas21002.h.*` files.

I've started making these changes, and will generate a PR probably in 7-10 days. The SensESP orientation example (over on https://github.com/BjarneBitscrambler/SensESP.git#OrientationV7) currently compiles and works on my ESP32, but there are a bunch of Issues, like this one, that I will incorporate at the same time.
