### ISSUE TITLE
board_buildscript problem

### ISSUE THREAD

**Issue by Ianknx** [SignalK/SensESP#277]
Hello

I am having problems with compile and upload with the following messages:-

oard_build.ldscriptWarning! '-Wl,-T' option for specifying linker scripts is deprecated. Please use 'board_build.ldscript' option in your 'platformio.ini' file.

Retrieving maximum program size .pio\build\d1_mini\firmware.elf
Checking size .pio\build\d1_mini\firmware.elf
*** [.pio\build\d1_mini\firmware.elf] Implicit dependency C:\Users\Ian\.platformio\platforms\espressif8266\builder\board_build' not found, needed by target .pio\build\d1_mini\firmware.elf'.

I have cloned the SensEsp directory into platformio and used the platformio.ini from within giving the following Warning:-

Warning! '-Wl,-T' option for specifying linker scripts is deprecated. Please use 'board_build.ldscript' option in your 'platformio.ini' file.
Retrieving maximum program size .pio\build\d1_mini\firmware.elf
Checking size .pio\build\d1_mini\firmware.elf

The script compiles and comes back with:-
Environment    Status    Duration
-------------  --------  ------------
d1_mini        SUCCESS   00:00:23.457
esp32dev       SUCCESS   00:00:44.042

on upload I get the warning

Warning! '-Wl,-T' option for specifying linker scripts is deprecated. Please use 'board_build.ldscript' option in your 'platformio.ini' file.

Then

d1_mini        SUCCESS   00:00:22.122
esp32dev       FAILED    00:00:33.390
===================================================== 1 failed, 1 succeeded in 00:00:55.512 ======================
The terminal process "C:\Users\Ian\.platformio\penv\Scripts\pio.exe 'run', '--target', 'upload'" terminated with e

I have replaced the board script as suggested in the warning  to:-

[espressif8266_base]
;this section has config items common to all ESP8266 boards
platform = espressif8266
board_build.ldscript = ldscript
build_flags =
   -Wall
   -Wno-reorder

And Save.

Building .pio\build\esp32dev\firmware.bin
esptool.py v2.6
Advanced Memory Usage is available via "PlatformIO Home > Project Inspect"
RAM:   [=         ]   6.7% (used 21932 bytes from 327680 bytes)
Flash: [==        ]  24.1% (used 474135 bytes from 1966080 bytes)
======================================================= [SUCCESS] Took 259.94 seconds =======================================================

Environment    Status    Duration
-------------  --------  ------------
d1_mini        SUCCESS   00:03:15.940
esp32dev       SUCCESS   00:04:19.936
======================================================== 2 succeeded in 00:07:35.877 ======================================================== 

On upload:-

Warning! '-Wl,-T' option for specifying linker scripts is deprecated. Please use 'board_build.ldscript' option in your 'platformio.ini' file.

A fatal error occurred: Timed out waiting for packet header
*** [upload] Error 2
======================================================== [FAILED] Took 31.90 seconds ========================================================

Environment    Status    Duration
-------------  --------  ------------
d1_mini        SUCCESS   00:00:25.838
esp32dev       FAILED    00:00:31.900
=================================================== 1 failed, 1 succeeded in 00:00:57.738 ===================================================
The terminal process "C:\Users\Ian\.platformio\penv\Scripts\pio.exe 'run', '--target', 'upload'" terminated with exit code: 1.

Regards

Ian

**Comment by ba58smith** [comment]
After much discussion on Slack, I don't believe this is an issue with SensESP, but rather, something in the environment of the end user. Closing this Issue.
