### ISSUE TITLE
Can not open SenseESP.gzz 

### ISSUE THREAD

**Issue by norbert-walter** [SignalK/SensESP#355]
I can not open the SenseESP.gzz with Fritzing V0.9.2 under Linux. Is it possible to make the schematic as PDF file? It is helpfully for viewing.

**Comment by ba58smith** [comment]
I had no trouble opening it. I did get a notice that one component couldn't be found, but then it opened.

This isn't really a part of SensESP - it's a PCB that one user created to allow someone to use a Wemos D1 Mini with several different types of sensors connected. If you want one, the information to order one is there in the same folder in the repo as the .fzz file. If you just want to see what it looks like, there's a photo of it also in the same folder.

**Comment by norbert-walter** [comment]
Thanks for the answare. I need a schematic with wires for all components. The picture in the same folder are not helpfully.

**Comment by ba58smith** [comment]
![image](https://user-images.githubusercontent.com/15186790/103891440-12cb3580-50a7-11eb-90b0-8872a1e3d578.png)

**Comment by ba58smith** [comment]
![image](https://user-images.githubusercontent.com/15186790/103891520-38f0d580-50a7-11eb-8f76-519db47ec4c0.png)

**Comment by ba58smith** [comment]
![image](https://user-images.githubusercontent.com/15186790/103891594-5aea5800-50a7-11eb-98fb-dafa6fb8cab0.png)

**Comment by norbert-walter** [comment]
Thanks for all
