### ISSUE TITLE
Duplicate sample values appear in CurveInterpolator transform's configuration web interface

### ISSUE THREAD

**Issue by BjarneBitscrambler** [SignalK/SensESP#375]
Entering and saving samples in the CurveInterpolator transform's web interface causes duplicates of the entered values to appear if the web interface is opened subsequent to the first save. Here's an example where the value pairs (0,0) and (6.28,6.28) were entered, saved, and then the configuration screen opened again: 
![duplicateexample](https://user-images.githubusercontent.com/68290965/108122145-b3265980-7058-11eb-9843-d47126ec10f0.png)

## Investigation
The Json manipulation code in `CurveInterpolator::get_configuration()` calls `jSamples.add(entry);` after calling `jSamples.createNestedObject();`   Since `createNestedObject()` already adds the input/output value pair, the unneeded `add()` call adds a second copy of each of the input/output values. See example in https://arduinojson.org/v6/api/jsonarray/createnestedobject/ for how it should be implemented - without the call to add().

Entering a single value pair of 0,0  yields the resulting json:
```
{"samples":[
   {"input":0,"output":0},
   {"input":0,"output":0}
   ]
}
```
when what is wanted is:
```
{"samples":[
   {"input":0,"output":0}
   ]
}
```

## Fix
Removing the extraneous `jSamples.add(entry);` corrects the problem, as tested on a d1_mini (ESP8266).  I'll open a PR shortly.

**Comment by ba58smith** [comment]
Fixed with #376.
