### ISSUE TITLE
Can't set curve config

### ISSUE THREAD

**Issue by ruedigerO** [SignalK/SensESP#382]
I used the example temperature_sender.cpp and try to configure CurveInterpolator via Web UI but always get an error 
"Error retrieving configuration /12V_alternator/temp/curve: Cannot convert undefined or null to object"

**Comment by ruedigerO** [comment]
Short update:
I tested it with a cloned version of the repository and this works!
Did you change anything regarding this functionality?

**Comment by ba58smith** [comment]
No, the CurveInterpolator code hasn't changed in a very long time.

**Comment by ba58smith** [comment]
How did you test it the first time, if not with a cloned version of the repo?

Regardless of your answer, should we close this Issue?

**Comment by ruedigerO** [comment]
As I am not an experienced C++ programmer, I used the steps described in "Getting started" (install VC, create a  platformio.ini, create a main.cpp and start the build). Everything was running fine with exception of the possibility to change settings of the CurveInterpolator via UI. 
In my second test I cloned it via "git clone" and I was able to compile and then change settings. 
Maybe there are changes at the UI/editor which are not committed?

You may close this issue now, but I think for people trying it in the future it would be helpful if it compiles from scratch.

**Comment by ba58smith** [comment]
I should have asked this when you first posted the issue: where did you see the error? On the browser screen, or in the Visual Studio serial monitor? That will help me figure out where the error is coming from. And if you have a screen shot of it, with anything else before it, that would be wonderful. Thanks.

**Comment by ruedigerO** [comment]
The issue is on the browser if you try to configure the curve.
![Bildschirmfoto 2021-03-08 um 16 41 20](https://user-images.githubusercontent.com/47414472/110343945-4ab21300-802d-11eb-9f76-b2dcb3da6517.png)
![Bildschirmfoto 2021-03-08 um 16 41 58](https://user-images.githubusercontent.com/47414472/110343969-51d92100-802d-11eb-975e-f27097ad6f5b.png)

**Comment by ruedigerO** [comment]
I think you may close this issue.
Maybe I used an old version of SensESP because now (with very. 1.0.5) it works fine.

Thanks & regards
