### ISSUE TITLE
Cleanup following move of orientation to external library

### ISSUE THREAD

**Issue by BjarneBitscrambler** [SignalK/SensESP#403]
The remnants of the old orientation code, which was left behind when PR #349 was abandoned, has caused compile errors recently when AdaFruit changed their FXOS/FXAS library.  @mairas has removed some of these remnants (in #402), but there still remains the AdaFruit AHRS (Attitude and Heading Reference System) library in `library.json` and `platform.ini`  This library is unneeded by any current sensors AFAIK, and can be deleted.

There were also some other improvements that #349 attempted to make, and that could be followed up on. These were: closing Issues #244, #216.

**Comment by mairas** [comment]
Caught this at the very last second! I'll still include these in the release.
