### ISSUE TITLE
Add a default password to OTA updates

### ISSUE THREAD

**Issue by mairas** [SignalK/SensESP#453]
At the moment, OTA updates can be applied to any device without passwords or anything. Add a default password and make it easy to change! Or alternatively, OTA updates should be disabled unless a password is set.

**Comment by JohnySeven** [comment]
Maybe add some builder method `enable_ota(bool enabled, string password)` would be option?

**Comment by mairas** [comment]
Yeah, I think that's the way to do it! I was somewhat fixated on adding the password as a preprocessor definition in platformio.ini, but it's better to not add "regular" configuration options in multiple places.

**Comment by mairas** [comment]
Fixed in #480.
