### ISSUE TITLE
Add a default password to the WiFi captive portal

### ISSUE THREAD

**Issue by mairas** [SignalK/SensESP#454]
If a SensESP device can't connect to the WiFi, it automatically sets up its own configuration access point. This access point has no password and makes it trivial to hijack a device in a harbor or anchorage, for example. Set a default password to the captive portal.

**Comment by JohnySeven** [comment]
Just to clarify: Is this only in case the WIFI configuration isn't hardcoded?

**Comment by mairas** [comment]
> Just to clarify: Is this only in case the WIFI configuration isn't hardcoded?

Yes. The idea is that, let's say, you're in a busy marina and you power on your electronics but the WiFi router is offline, then any SensESP devices (that don't have hardcoded WiFi config) would enable the config AP, allowing any neighbor to hijack the device.

**Comment by mairas** [comment]
Fixed in #481.
