### ISSUE TITLE
Reimplement previously removed "standard sensors"

### ISSUE THREAD

**Issue by mairas** [SignalK/SensESP#455]
There are ~four~ five system information sensors, previously called standard sensors, that were enabled by default and could be triggered on or off using SensESPAppBuilder:

- SystemHz
- FreeMem
- Uptime
- IPAddrDev
- WifiSignal

SensESPAppBuilder needs to have convenience methods to enable these:

- `enable_system_hz_sensor()`
- `enable_free_mem_sensor()`
- `enable_uptime_sensor()`
- `enable_ip_address_sensor()`
- `enable_wifi_signal_sensor()`

And additionally, one convenience method to enable all of these. My proposal for the name:

- `enable_system_info_sensors()`

**Comment by ba58smith** [comment]
I like `system_info_sensors`.

**Comment by JohnySeven** [comment]
Like it! Library user have it all under control!

**Comment by mairas** [comment]
Fixed in #472.
