### ISSUE TITLE
Disable remote debugging by default

### ISSUE THREAD

**Issue by mairas** [SignalK/SensESP#458]
I don't think many people actually use (or even know about) the telnet debugging facilities provided by the `RemoteDebug` library. Also, the remove debugging interface is arguably a vulnerability. Let's disable it by default (while still keeping serial debugging enabled).

**Comment by JohnySeven** [comment]
Totally agree! This is something I've never used, get it disabled and allow folks using it (if anybody?) to enable it with ease.
