### ISSUE TITLE
RFE: Add integration with homeassistant

### ISSUE THREAD

**Issue by mgrouch** [SignalK/SensESP#524]
Add integration with homeassistant.

Homeassistant being more generic is more supported than SignalK and has way bigger community.

Thanks

**Comment by dmtamsen** [comment]
Will esphome.io not better suit your needs then?

**Comment by mgrouch** [comment]
Thanks. I didn’t know it existed. 
Looks awesome by reading. 
Homeassistant automations capabilities are much better than SignalK. 
Now a question why SensESP team is not partnering with esphome.io?
I think it be better than some of 
SignalK components and some of SensESP be integrated into homeassistant and esphome.io. 

Again boat is much like a home with some more specific needs. Home automation community grows rapidly and it’s much bigger than boating. 
I think boating software should just integrate more into it to avoid reinventing stuff which will be tested less overall (less users)
Just random thoughts. 

thanks for the link, I’ll study more

**Comment by mairas** [comment]
Not in focus. Closing.
