### ISSUE TITLE
CurveInterpolator does not store samples permanently

### ISSUE THREAD

**Issue by ruedigerO** [SignalK/SensESP#566]
When samples are added/changed via WebUI the values are not stored permanently (after restarting the ESP the default samples are back)

**Comment by mairas** [comment]
> Maybe a little more documentation about this nice feature would be helpful.

Yes, I'd love that! Could you write some?

**Comment by ruedigerO** [comment]
I don’t think that’s a good idea, cause I am a beginner in programming C++
and a lousily writer :-(
