### ISSUE TITLE
ESP32

### ISSUE THREAD

**Issue by andyrbarrow** [SignalK/SensESP#57]
Do you have an example that compiles with ESP32? I can't get any of the examples to compile, even after changing platformio.ini.

**Comment by joelkoz** [comment]
I don't at the moment, but I just received my ESP32 in the mail today for my next project.  I'll give it a go and see what happens.

**Comment by andyrbarrow** [comment]
Thanks. It appears the issue is with ESP8266Random. I've been trying to
work my way through the code to figure out opportunities for porting to the
ESP32.
*Andy Barrow*

*email: *andy@sailor.nu
*tel (mx):* +52 322 104 2189
*tel (us):* +1 925 270 0473
*Skype:* abarrow

**Comment by andyrbarrow** [comment]
I fiddled with it a bit, but I can't get it to work. I took out ESP8266Random and replaced the RANDOM_REG32 definition with a variable that gets a random number from esp_random(). It fixed a few things, but there are lots of other calls to 8266 specific libraries.

**Comment by joelkoz** [comment]
My guess is that fairly high up the chain, a compiler directive needs to be used in the SensESP code to select an ESP32 version of a particular library (vs. an ESP8266).  For example:


#ifdef ESP8266
  #include <ESP8266mDNS.h> // Include the mDNS library
#elif defined(ESP32)
  #include <ESPmDNS.h>
#endif

**Comment by andyrbarrow** [comment]
Yes, that's what I was doing. I'll keep hacking away at it.

**Comment by Haimana** [comment]
> Do you have an example that compiles with ESP32? I can't get any of the examples to compile, even after changing platformio.ini.

Any progress with ESP32? Thanks

**Comment by ba58smith** [comment]
@Haimana, as far as I know, no one is working on it. Sorry.

**Comment by ba58smith** [comment]
See PR #115 .

**Comment by ba58smith** [comment]
Closed. See PR #118.
