### ISSUE TITLE
Data logger example

### ISSUE THREAD

**Issue by mgrouch** [SignalK/SensESP#602]
A data logger of various sensors to SD card with periodic deep sleep and web service to request logs would be 
very useful addition to examples.

Some part of the code can be probably taken from here

https://randomnerdtutorials.com/esp32-data-logging-temperature-to-microsd-card/

Thanks

**Comment by mairas** [comment]
Doable, of course, but quite random and unrelated. If you decide to do this, create a separate repo for the project and then make a PR for adding a link to the https://signalk.org/SensESP/pages/additional_resources/ page.

Thanks
