### ISSUE TITLE
Set a configurable interval for sending data to SK

### ISSUE THREAD

**Issue by Haimana** [SignalK/SensESP#72]
Hello again,

There is some way to set the interval of time to send data to SK? Will be nice if is possible to set this for each used sk_path. 

Also, to disable sending SystemHZ, Uptime, Freemem and so on, there is any other way to do it?
I did it by commenting the specific lines in sensesp_app.cpp but I don;t know if this is the best way to do it.

Thank you,
Seb

**Comment by ba58smith** [comment]
@Haimana, I don't think there is currently a way to set the time interval. (From what I can tell, each sensor type has its own interval.) I agree, it would be nice, as some things don't need updated multiple times per second. However, I don't think you'll run into any limitations by using the defaults.

**Comment by ba58smith** [comment]
That's the only way to disable the system data (commenting out the appropriate lines).

**Comment by ba58smith** [comment]
This has been done for AnalogInput with PR #76 . Once that PR has been approved, I will look at doing it for all sensors that don't have it yet.

**Comment by ba58smith** [comment]
This has now been done for OneWire Temperature sensor with PR #82.

**Comment by ba58smith** [comment]
All sensors for which a configurable read interval makes sense have now been done, pending review and merge of PR #76 and PR #82.
