### ISSUE TITLE
Not saving wifi client credentials in setup screen.

### ISSUE THREAD

**Issue by imoldovavan** [SignalK/SensESP#729]
In wifi setup screen there is no indication in the output terminal that the credentials are saved. Hitting the save button does nothing. If I switch back and forth between SignalK tab and WiFi the credentials disappear. 

Here is the log after I reset the device.

`
rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13232
load:0x40080400,len:3028
entry 0x400805e4
D (49) configurable.cpp: Loading configuration for path '/system/hostname' from '/qLsPBGc6u2S+SPgr87i11VrDlCE='
D (64) configurable.cpp: Saving configuration path /system/hostname to file /qLsPBGc6u2S+SPgr87i11VrDlCE=
I (105) configurable.cpp: Could not find configuration for path /System/WiFi Settings
D (105) networking.cpp: Enabling Networking
D (130) Arduino: Arduino Event: 0 - WIFI_READY
V (795) Arduino: STA Started
V (797) Arduino: Configuring Station static IP: 0.0.0.0, MASK: 0.0.0.0, GW: 0.0.0.0
D (797) Arduino: Arduino Event: 2 - STA_START
V (814) Arduino: STA Stopped
D (815) Arduino: Arduino Event: 3 - STA_STOP
V (817) Arduino: AP Started
D (817) Arduino: Arduino Event: 10 - AP_START
I (817) networking.h: WiFi Access Point enabled, SSID: my-sensesp-project
I (823) networking.h: IP address of Device: 192.168.4.1
I (829) networking.cpp: Starting access point my-sensesp-project
I (865) configurable.cpp: Could not find configuration for path /system/httpserver
D (866) http_server.h: HTTPServer instance created
I (872) configurable.cpp: Not loading configuration: no config_path specified: 
I (873) configurable.cpp: Not loading configuration: no config_path specified: 
D (884) configurable.cpp: Loading configuration for path '/System/Signal K Settings' from '/7NAVR03_FL3ag9_pt1mBQlpDmeM='
D (896) base_button.h: Button handler started
I (896) configurable.cpp: Not loading configuration: no config_path specified: 
I (903) configurable.cpp: Not loading configuration: no config_path specified: 
I (941) configurable.cpp: Could not find configuration for path /Sensors/Analog Input/Voltage
I (972) configurable.cpp: Could not find configuration for path /Sensors/Digital Input 2/Value
D (973) main.cpp: Digital input value changed: 1
I (977) http_server.h: HTTP server started
E (978) Arduino: Failed adding service http.tcp.

D (982) signalk_ws_client.cpp: Starting SKWSClient
E (987) Arduino: Failed adding service signalk-sensesp.tcp.

I (987) signalk_ws_client.cpp: Initiating websocket connection with server...
D (999) signalk_ws_client.cpp: Websocket is connecting to Signal K server on address 10.42.0.1:3000
I (999) discovery.cpp: mDNS responder started for hostname 'my-sensesp-project'
D (1008) signalk_ws_client.cpp: No prior authorization token present.
D (1021) signalk_ws_client.cpp: Preparing a new access request
D (1027) signalk_ws_client.cpp: Access request: {"clientId":"d4205d25-40c2-df5b-a249-49d0d0e87820","description":"SensESP device: my-sensesp-project","permissions":"readwrite"}
D (1042) signalk_ws_client.cpp: Access request url: http://10.42.0.1:3000/signalk/v1/access/requests
V (1051) Arduino: url: http://10.42.0.1:3000/signalk/v1/access/requests
D (1057) Arduino: protocol: http, host: 10.42.0.1 port: 3000 url: /signalk/v1/access/requests
D (1066) Arduino: request type: 'POST' redirCount: 0

D (1403) main.cpp: Analog input value: 0.142000
D (1903) main.cpp: Analog input value: 0.142000
D (2403) main.cpp: Analog input value: 0.142000
D (2903) main.cpp: Analog input value: 0.142000
D (3403) main.cpp: Analog input value: 0.142000
D (3903) main.cpp: Analog input value: 0.142000
D (4403) main.cpp: Analog input value: 0.142000
D (4903) main.cpp: Analog input value: 0.142000
D (5403) main.cpp: Analog input value: 0.142000
D (5903) main.cpp: Analog input value: 0.142000
I (6075) Arduino: select returned due to timeout 5000 ms for fd 52
D (6076) Arduino: failed connect to 10.42.0.1:3000
W (6076) Arduino: error(-1): connection refused
W (6079) Arduino: error(-4): not connected
D (6083) Arduino: tcp is closed

W (6086) signalk_ws_client.cpp: Can't handle response -1 to access request.
D (6092) signalk_ws_client.cpp: 
I (6096) signalk_ws_client.cpp: Initiating websocket connection with server...
D (6102) signalk_ws_client.cpp: Websocket is connecting to Signal K server on address 10.42.0.1:3000
D (6111) signalk_ws_client.cpp: No prior authorization token present.
D (6117) signalk_ws_client.cpp: Preparing a new access request
D (6135) configurable.cpp: Saving configuration path /System/Signal K Settings to file /7NAVR03_FL3ag9_pt1mBQlpDmeM=
D (6149) signalk_ws_client.cpp: Access request: {"clientId":"eae8c8cb-4b2b-9a52-1356-0b7f59a44845","description":"SensESP device: my-sensesp-project","permissions":"readwrite"}
D (6154) signalk_ws_client.cpp: Access request url: http://10.42.0.1:3000/signalk/v1/access/requests
V (6163) Arduino: url: http://10.42.0.1:3000/signalk/v1/access/requests
D (6169) Arduino: protocol: http, host: 10.42.0.1 port: 3000 url: /signalk/v1/access/requests
D (6177) Arduino: request type: 'POST' redirCount: 0

D (6403) main.cpp: Analog input value: 0.142000
D (6903) main.cpp: Analog input value: 0.142000
`

**Comment by imoldovavan** [comment]
If I connect the pi to the esp32 ap, everything seems to be working. Not sure if this info is of any help :)

**Comment by donmarlin** [comment]
I can confirm this. Using the Beta version. All was working well after upgrading from Alpha. 
I then did factory reset using the web UI to clear the nvram.  
Now wifi wont connect to the network. I have tried to set the wifi credentials in the UI but they don't seem to be saved. 
I also tried to hardcode wifi in builder config but nothing seems to work.

**Comment by grhitch** [comment]
I can also confirm this problem using SensESP 3.0.0-beta.1.
Hardware is various, but includes Halmet v1.0.

1) Hard coded wifi settings are not effective, although changing the hostname here does work.
2) Web interface scans wifi and finds access points, but cannot connect and does not save any changes. 

I have tried to get to the bottom of this, but unfortunately do not have the skills  to make any real progress. 

I did manage to confirm that SPIFFS does exist. I also confirmed that a file is created when starting with a 'blank' device. I added a couple of debug lines that yielded:
> FILE: qLsPBGc6u2S+SPgr87i11VrDlCE=
> File size: 31 bytes

Watching the HTTP messages didn't show anything that was obviously "save".

An abbreviated log file is attached

[device-monitor-240824-125808.log](https://github.com/user-attachments/files/16735003/device-monitor-240824-125808.log)

**Comment by mairas** [comment]
I was able to reproduce this and just fixed the problem. I had made some last-minute changes in the frontend after which I got distracted and didn't test them properly.

Until I release a new beta version, you can use the latest development version by commenting out the SensESP dependency in your project `platformio.ini` file and adding the following:

```
https://github.com/SignalK/SensESP.git
```
