### ISSUE TITLE
discussion place? slack link seems dead

### ISSUE THREAD

**Issue by aktxyz** [SignalK/SensESP#731]
Hi Folks,

I have SignalK up and running with several ESP32 devices sending data ... woo hoo.

For 2 of these devices (connected to 30kw generators), I would like to be able to SEND some messages to the ESP32, mainly to trigger a shutdown by opening a relay that connects to the fuel rack solenoid.

Is there a signalK way to SEND info?

The slack link on this page does not seem to be working FYI
https://signalk.org/SensESP/pages/get_in_touch/
http://slack-invite.signalk.org/

**Comment by mairas** [comment]
Thanks for the heads-up! Signal K switched from Slack to Discord and I forgot to fix the references in the SensESP repo...

To gain access to the Discord server, follow the invite link at http://signalk.org.
