### ISSUE TITLE
Missing: "sensesp/transforms/threshold.h"

### ISSUE THREAD

**Issue by StefanKrax** [SignalK/SensESP#776]
Hello @mairas, 

first of all, you do a great job! 

I use the example https://github.com/SignalK/SensESP/blob/main/examples/relay_control.cpp for my motor and motor room SensESP. I want to use the threshold to switch the coolant pump on, but the file "sensesp/transforms/threshold.h" is missing. 

I use the actual 3.0.0-beta.6  with the include line:
#include "sensesp/transforms/threshold.h"

regards, Stefan

**Comment by StefanKrax** [comment]
With 3.0.1 repaired.

**Comment by mairas** [comment]
Oopsie, sorry - I definitely should've tagged this PR when I fixed the issue! Didn't intend to keep you hanging intentionally, apologies for that!
