### ISSUE TITLE
UnknownPackageError: Could not find the package with 'SignalK/SensESP @ ^3.1.0' requirements for your system 'windows_amd64'

### ISSUE THREAD

**Issue by dagnum** [SignalK/SensESP#802]
Whenever I try to use the latest 3.1.0 on both of my PCs I get this error:
UnknownPackageError: Could not find the package with 'SignalK/SensESP @ ^3.1.0' requirements for your system 'windows_amd64'

Using Seeed S3 Board

[Relay Controller.zip](https://github.com/user-attachments/files/18223488/Relay.Controller.zip)

**Comment by TMaketa** [comment]
[Relay.Controller.zip](https://github.com/user-attachments/files/18229142/Relay.Controller.zip)

**Comment by dagnum** [comment]
Thank you trying this now...can you tell me what was changed?

**Comment by mairas** [comment]
Ahh. Sorry about that! I actually didn't release 3.1.0 yet even though I already anticipated it in the ini file. Change your SensESP dependency from 3.1.0 to 3.0.0 and that should fix it.

**Comment by dagnum** [comment]
Ahh thank you! Trying it now!
