### ISSUE TITLE
"Unconfigured SensESP Device" SSID s/b unique

### ISSUE THREAD

**Issue by ba58smith** [SignalK/SensESP#86]
If you happen to have two unconfigured SensESP devices, they both get the same the SSID ("Unconfigured SensESP Device"), and the same IP address.  It would be better if the name were unique to the device, using some part of the device's Hostname to make it unique. It would be best if each had a unique name AND a unique IP address.

This problem is made worse by the fact that some ESP's will broadcast their SSID (with the name "Unconfigured SensESP Device") even after they have successfully connected to the network. (That's another issue, of course. Issue # 87, in fact. )

**Comment by ba58smith** [comment]
I've spent hours looking at this, and I can't make any progress on it. I can't sort out the confusion between the `hostname` and the `SSID`, and also, I think the SSID may be cached on the ESP or on all of my wifi-enabled devices, because even when I change the string "Unconfigured SensESP Device" to something else, it STILL broadcasts "Unconfigured SensESP Device".

**Comment by mairas** [comment]
I can have a look soon(ish). Tasmota would be a good reference project for this one - the Tasmota devices advertise with an SSID like Tasmota-1234 (don't remember the exact format), where the number is unique for each sensor, probably taken from the MAC address of the wifi device.

**Comment by ba58smith** [comment]
One challenge with this is that there seems to be a bug in WiFiManager in which the SSID and PW of the saved network are not erased from the flash memory on the ESP8266 when `resetSettings()` is called (which just calls `disconnect()`). This is still an open Issue with WiFiManager: https://github.com/tzapu/WiFiManager/issues/142.

**Comment by ba58smith** [comment]
See PR #108.

**Comment by ba58smith** [comment]
Fixed with PR #108
